trigger: none

pool:
  vmImage: 'ubuntu-latest'

variables:
  workingDirectory: 'environments/QA'
  serviceConnection: 'dhdp-infra-service-connection'
  backendResourceGroup: 'dhdp-qa-rg'
  backendStorageAccount: 'dhdpqasf'
  backendContainerName: 'qatfstate'
  backendKey: 'qa/terraform.tfstate'
stages:
  - stage: Lint
    displayName: 'Terraform Lint'
    jobs:
      - job: Lint
        displayName: 'Lint Terraform Code'
        steps:
          - checkout: self
            persistCredentials: true

          - script: |
              echo "Installing tflint..."
              curl -s https://raw.githubusercontent.com/terraform-linters/tflint/master/install_linux.sh | bash
              tflint --init
              tflint --chdir=$(workingDirectory) || echo "⚠️ TFLint warnings detected, but not failing the pipeline."
            displayName: 'Run tflint'

  - stage: Scan
    displayName: 'Terraform Security Scan'
    dependsOn: Lint
    jobs:
      - job: Scan
        displayName: 'Checkov Terraform Scan'
        steps:
          - checkout: self

          - script: |
              echo "Installing Checkov..."
              pip install checkov
            displayName: 'Install Checkov'

          - script: |
              echo "Running Checkov scan..."
              checkov -d $(workingDirectory) -o sarif --output-file-path checkov-report.sarif || echo "Checkov completed with findings"
            displayName: 'Run Checkov with SARIF Output'

          - task: PublishBuildArtifacts@1
            displayName: 'Publish Checkov SARIF Report'
            inputs:
              PathtoPublish: 'checkov-report.sarif'
              ArtifactName: 'CheckovReport'
              publishLocation: 'Container'