trigger: none

pool:
  name: Default

variables:
  workingDirectory: environments/QA
  serviceConnection: dhdp-infra-sc
  backendResourceGroup: dhdp-qat-resource-group
  backendStorageAccount: dhdplabsa
  backendContainerName: tfstate
  backendKey: qa.terraform.tfstate

stages:
  - stage: Lint
    displayName: Terraform Lint
    jobs:
      - job: Lint
        displayName: Lint Terraform Code
        steps:
          - checkout: self
            persistCredentials: true

          - task: PowerShell@2
            displayName: Install and run TFLint
            inputs:
              targetType: inline
              script: |
                tflint --init
                if (-not $?) {
                  Write-Warning "⚠️ TFLint init failed, but continuing."
                }

                tflint --chdir=$(workingDirectory)
                if (-not $?) {
                  Write-Warning "⚠️ TFLint warnings detected, but not failing the pipeline."
                }

  - stage: Scan
    displayName: Terraform Security Scan
    dependsOn: Lint
    jobs:
      - job: Scan
        displayName: Checkov Terraform Scan
        steps:
          - checkout: self

#          - task: UsePythonVersion@0
 #           displayName: Install Python 3.x
  #          inputs:
   #           versionSpec: 3.x
    #          addToPath: true

          - script: |
              echo "Adding Python to PATH"
              set PATH=C:\Program Files\Python313\;C:\Program Files\Python313\Scripts\;%PATH%
              echo "Installing Checkov..."
              pip install --disable-pip-version-check --no-cache-dir checkov
            displayName: Install Checkov

          - script: |
              echo "Running Checkov scan..."
              checkov -d $(workingDirectory) -o sarif --output-file-path checkov-report.sarif || echo "Checkov completed with findings"
            displayName: Run Checkov with SARIF Output

          - task: PublishBuildArtifacts@1
            displayName: Publish Checkov SARIF Report
            inputs:
              PathtoPublish: checkov-report.sarif
              ArtifactName: CheckovReport
              publishLocation: Container

  - stage: Init
    displayName: Terraform Init
    dependsOn: Scan
    jobs:
      - job: Init
        displayName: Terraform Initialization
        steps:
          - checkout: self
            persistCredentials: true

          - script: |
              rd /s /q .terraform
              del /q .terraform.lock.hcl 2>NUL
            displayName: Clean .terraform and lockfile

          - script: |
              echo "##vso[task.setvariable variable=ARM_USE_OIDC]true"
              echo "##vso[task.setvariable variable=ARM_CLIENT_ID]$(servicePrincipalId)"
              echo "##vso[task.setvariable variable=ARM_TENANT_ID]$(tenantId)"
              echo "##vso[task.setvariable variable=ARM_SUBSCRIPTION_ID]$(subscriptionId)"
            displayName: Set OIDC Auth Variables

          - task: TerraformInstaller@1
            displayName: Install Terraform 1.5.7
            inputs:
              terraformVersion: 1.5.7

          - script: terraform -version
            displayName: Show Terraform Version

          - task: TerraformTaskV4@4
            displayName: Terraform Init
            inputs:
              provider: azurerm
              command: init
              workingDirectory: $(workingDirectory)
              backendServiceArm: $(serviceConnection)
              backendAzureRmResourceGroupName: $(backendResourceGroup)
              backendAzureRmStorageAccountName: $(backendStorageAccount)
              backendAzureRmContainerName: $(backendContainerName)
              backendAzureRmKey: $(backendKey)
              backendAzureRmUseOIDC: true
              useTerraformVersion: 1.5.7
